// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZCiLZgFRh8NhpD4MGfxWnLILqcbmtdZ8',
    appId: '1:850443119816:web:fd113222e28091217289fd',
    messagingSenderId: '850443119816',
    projectId: 'cysterease',
    authDomain: 'cysterease.firebaseapp.com',
    storageBucket: 'cysterease.firebasestorage.app',
    measurementId: 'G-WLG9GQPC40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOqDwvJz76xeoE5WX6TrgwchHbMyyVKUU',
    appId: '1:850443119816:android:36c27b87483e4c347289fd',
    messagingSenderId: '850443119816',
    projectId: 'cysterease',
    storageBucket: 'cysterease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkb_N214XRJYvtQD-Z1BeMqvmyCOqbU5U',
    appId: '1:850443119816:ios:4a29008dd0f15b937289fd',
    messagingSenderId: '850443119816',
    projectId: 'cysterease',
    storageBucket: 'cysterease.firebasestorage.app',
    iosBundleId: 'com.example.cysterease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkb_N214XRJYvtQD-Z1BeMqvmyCOqbU5U',
    appId: '1:850443119816:ios:4a29008dd0f15b937289fd',
    messagingSenderId: '850443119816',
    projectId: 'cysterease',
    storageBucket: 'cysterease.firebasestorage.app',
    iosBundleId: 'com.example.cysterease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZCiLZgFRh8NhpD4MGfxWnLILqcbmtdZ8',
    appId: '1:850443119816:web:01297af062d7ddf27289fd',
    messagingSenderId: '850443119816',
    projectId: 'cysterease',
    authDomain: 'cysterease.firebaseapp.com',
    storageBucket: 'cysterease.firebasestorage.app',
    measurementId: 'G-SBKRS9Z9GZ',
  );
}
